### PR TITLE
Skeleton structure improved

### PR DESCRIPTION
**Pull request by rustemgareev**
I hope all changes are visible now and  are understandable.

### CODE REVIEW

**Comment by rustemgareev** [comment]
Also as I've mentioned earlier, I'm new for github and I don't know how to place two files in one pull request, sorry.

**Comment by kamlekar** [comment]
yeah no problem. Looks good to me but there is only one problem, the comments are SHOUTING :). Anyway, I will take your request and do require changes. Thanks.

**Comment by rustemgareev** [comment]
Sorry for this but I should distinct them from yours in some way. Hope you understand my suggestions, it's the main thing. Also, I have other points for improvements. Do you have time to discuss them here?

**Comment by kamlekar** [comment]
Yes sure, I can reply whenever I get time. if you have any suggestions, please add as a new issue so that we can keep track of things. Also, no need of trying to distinct the comments or code from next time. Once again, thanks for contributing :)

**Comment by kamlekar** [comment]
In these changes, you removed SVG sprite loading. Please check `section/_head.html`.

**Pull request merged**
