### PR TITLE
Add variables for paths, added 'gulp-data' code

### PR DESCRIPTION
**Pull request by rustemgareev**
Set paths to base templates and sources through variables. Added 'gulp-data' for adding data.json to site.
<strong>You need to create 'data.json' file in <em>site/data/</em> folder</strong>

### CODE REVIEW

**Comment by kamlekar** [comment]
Hi @rustemgareev did you check? is it working fine?

**Comment by rustemgareev** [comment]
Hi, yes I checked it (except bundle-svgs). sass / js / htmls work fine. The only possible mistakes can be with mispellings (I haven't copy/pasted from notepad++, I inputed directly in browser github). But overall this works.

**Comment by kamlekar** [comment]
Ok. There is a small change. Keep "assets/" path in a separate variable. So that when user changes this path, all paths changes automatically. _reusable concept_. You can edit this PR by visiting "Files changed" tab, I think. and also, you added `gulp-data` but it was never added in package.json. (_better to remove that line, we can see later_). Please work with patience with me :)

**Comment by rustemgareev** [comment]
I sent package.json with "gulp-data" in another pull request (I still don't know how to edit multiple files in one pull request).
As for "assets" in separate variable - I don't think. For example, people can have this structure:
|site
|__assets
|__|__css
|__|__js
|__shop
|__data
|__images

**Comment by rustemgareev** [comment]
So I don't think users will have trouble to change 20 signs of code.

**Comment by kamlekar** [comment]
ok :+1:  will merge this once I fix the current issue which I am struggling to fix from morning.

**Pull request merged**
