### PR TITLE
Improve page structure for easier files including

### PR DESCRIPTION
**Pull request by rustemgareev**
Hi. Please change structure of <em>skeleton-content.html</em> so people could include additional css and js files on selected pages (in <em>include_head</em> and <em>include_footer</em> blocks respectively).

### CODE REVIEW

**Comment by kamlekar** [comment]
Hi @rustemgareev thanks for your inputs. the `_head.html` is supposed to keep all the files related to `<head>` tag. So please update your pull request as necessary.

**Comment by kamlekar** [comment]
Also, there is already functionality similar to `include_head`. Please check `sections/_head.html` file.

**Comment by rustemgareev** [comment]
Yes, but it works "globally", I mean if user want to include specific files on "index-2.html" only, he can extend block <em>"include_head"/"include_footer"</em> with required files. Please see my second pull request with changes to index.html. Sorry I'm beginner to github and I couldn't change two files in one pull request.

**Comment by kamlekar** [comment]
No problem :). Anyway, I will close this PR and check the other.

**Pull request closed without merging**
