### PR TITLE
Revert "Add variables for paths, added 'gulp-data' code"

### PR DESCRIPTION
**Pull request by kamlekar**
Reverts kamlekar/HTML-Skinning-Boilerplate#26

### CODE REVIEW

**Comment by kamlekar** [comment]
There were issues in PR https://github.com/kamlekar/HTML-Skinning-Boilerplate/pull/26.

**Comment by rustemgareev** [comment]
What are issues?

**Comment by kamlekar** [comment]
Hi @rustemgareev  I wasn't able to run `gulp watch` in CLI.

**Comment by rustemgareev** [comment]
Have you added empty data.json? in site/data/

**Comment by kamlekar** [comment]
No, I haven't. Please send another PR with all the changes. And do we need `gulp-data`? if needed, please also send package.json change.

**Comment by rustemgareev** [comment]
#22 is PR with package.json
#26 has descriptions that you should add data.json to "site/data/" folder.

**Comment by kamlekar** [comment]
But I don't think the error is related to empty json file or gulp-data. Is it working fine in your local?

**Comment by rustemgareev** [comment]
What is written in console?
No matter empty or filled - data.json should be in "site/data/" folder.
This works fine to me.

**Comment by kamlekar** [comment]
Here is the screenshot of the issue:

http://i.imgur.com/bnuxfjl.png

**Comment by kamlekar** [comment]
Also, `site` directory is supposed to have only production ready (or final) code files. So, can we keep the empty `data.json` file outside of `site` folder?

**Comment by rustemgareev** [comment]
This issue is unknown to me=) but I think it's with mispelling, I should check gulpfile.js.
Also error will appear if data.json is not on correct directory (that happened to me sometimes).

As for data.json outside of site - I think no. For example if you want to use images in data.json, they should be on site, and data.json on site. But it's not problem - I think it's very useful, people can fill they site with data, not just static texts.

**Comment by rustemgareev** [comment]
Yeah, problem is detected - one closing ) missed:
127 string
.pipe(gulp.dest(basePath.site);
shoulde be
.pipe(gulp.dest(basePath.site));

**Comment by kamlekar** [comment]
Yup, the issue is that you missed one closing parenthesis in gulpfile.js :). Please check it from next time. Clearly, manual testing is taking more time. I need to assign myself to attach Travis asap. And also please add all related changes in one PR (_I know you are struggling to add all in one PR, but I know you will figure it out soon_). Please send me new PR will all changes.

**Comment by kamlekar** [comment]
@rustemgareev Also, I created new branch, [pr-branch](https://github.com/kamlekar/HTML-Skinning-Boilerplate/tree/pr-branch). Until we integrate travis we can't take risk on testing the new changes on working master branch. So, I added new branch. Please send PR to that branch.

**Comment by kamlekar** [comment]
@rustemgareev you can contact me on my mail id: kamlekar.venkatesh[at]gmail[dot]com. Once you say "hi" there, I will delete this message for privacy purpose.

**Pull request merged**
