### PR TITLE
Added "gulp-data" dependency to package.json

### PR DESCRIPTION
**Pull request by rustemgareev**

### CODE REVIEW

**Comment by kamlekar** [comment]
Hi. If I am merging the pull request, somehow the `+` in the updated line is also being added. Please check it once. (_Happened with your previous PR as well, check [here](https://github.com/kamlekar/HTML-Skinning-Boilerplate/blob/master/templates-pre/sections/_skeleton-content.html)_)

**Comment by rustemgareev** [comment]
Ups, I'm sorry. I do all changes in browser, will try to fix it.

**Comment by kamlekar** [comment]
:) that is why it is must to add automated testing like travis soon. if you know about it please add it.

**Comment by rustemgareev** [comment]
No, I'm sorry, I don't familiar with it.

**Pull request merged**
