### PR TITLE
Improve page structure for easier files including

### PR DESCRIPTION
**Pull request by rustemgareev**
Hi. Please change structure of skeleton-content.html so people could include additional css and js files on selected pages (in include_head and include_footer blocks respectively).

### CODE REVIEW

**Comment by kamlekar** [comment]
As I commented on your other pull request, the `head` tag content is being already managed in "sections/_head.html". Please check the line `{% include "sections/_head.html" %}`. So, please update your pull request.

**Comment by kamlekar** [comment]
Is this working for you? Sorry, I still didn't what exactly it will do. Please explain me.

**Comment by rustemgareev** [comment]
I understand your current skeleton structure well and know about "_head.html", but my suggestions will improve overall working with your boilerplate. Is communicate in this thread ok to you?

**Comment by kamlekar** [comment]
Yeah sure, I have no problem communicating here.

**Comment by rustemgareev** [comment]
OK, So first I should tell it is AWESOME!!! Great work. But still may have improvements with practical templating.

**Comment by kamlekar** [comment]
Yes thanks. But I am unable to understand why you add `{% block include_head %}` in `index.html` instead where we can just add the necessary links and scripts directly. or maybe you are missing some files to attach?

**Comment by rustemgareev** [comment]
So I will explain about working with templates.
Imagine you need to add some page-specific styles or page-specific scripts (ie. You have blog site and have one page with shop and you need shop styles only on one page. )
Your current template index.html works only with "content" part. So you have no way to change header part or footer part in index.html. My improvement is to extend index.html with blocks "include_head" or "include_footer" so you will have specific files only on specific pages.

**Comment by rustemgareev** [comment]
And this will work because skeleton structure will be such:
'<head>
  <title>My Site</title>
  <link src="global.css">
  <link src="page-specific.css">
</head>'
And the same with footer. Some time you need call plugins only on specific pages so you adding script not globally but only in index.html. And this will work (see my changes to _skeleton).

**Comment by kamlekar** [comment]
hmm yes I understood that but we need to define the code in `block` when we are planning to reuse the block. But here, we will use it only once i.e in that specific page. So, if you need page-specific styles or scripts, you can just add them directly instead of maintaining in `block`. Like:

	{% extends "sections/_skeleton-content.html" %}
	{% block content %}
		
		<link rel="stylesheet" href="#"/>

		

		

	{% endblock %}

But you are saying you also did changes to `_skeleton-content.html` which I can't see here. Please check your PR once.

**Comment by rustemgareev** [comment]
It won't work because block content starts inside <body> tag but we need to add styles in <head> tag.

**Comment by rustemgareev** [comment]
inside body tag

**Comment by rustemgareev** [comment]
It won't work because block content starts inside body tag but we need to add styles in head tag.

**Comment by kamlekar** [comment]
yeah then you definitely missed files to add to this PR. I can see only one file change here i.e index.html.

**Comment by rustemgareev** [comment]
Ok I will check skeleton and will show you improvements

**Comment by kamlekar** [comment]
:+1: Thanks. I will close this PR. Please send a new PR with updated changes :)

**Pull request closed without merging**
